# Configuración del servidor del Gateway
server:
  port: 9000 # El puerto donde escuchará el Gateway

# Configuración de Spring Cloud Gateway
spring:
  application:
    name: api-gateway # Nombre de nuestra aplicación Gateway
  cloud:
    gateway:
      # Definición de las rutas
      routes:
        - id: auth_service_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/**, /auth/**
      # --- CONFIGURACIÓN DE CORS GLOBAL ---
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:63342"
              - "http://localhost:9000"
              - "http://127.0.0.1:5500"
              - "http://localhost:5500"
              - "http://localhost"
              - "*" # Solo para pruebas, eliminar en producción
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    enabled: false